target-version = "py311"
line-length = 120

[lint]
select = ["E", "F", "I", "N", "W", "UP"]
ignore = ["E501"]

[lint.per-file-ignores]
"tests/**/*.py" = ["E402"]
"src/backend/tests/**/*.py" = ["E402"]

[format]
quote-style = "double"
indent-style = "space"
