"""sync constraints after schema merge

Revision ID: aa3d04a68965
Revises: 91e18f0d7446
Create Date: 2026-08-10 15:15:33.312982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa3d04a68965'
down_revision: Union[str, Sequence[str], None] = '91e18f0d7446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_app_user_phone'), table_name='app_user', schema='app', postgresql_where='(phone IS NOT NULL)')
    op.create_unique_constraint(op.f('uq_app_user_phone'), 'app_user', ['phone'], schema='app')
    op.drop_constraint(op.f('ck_app_user_role_valid'), 'app_user', schema='app', type_='check')
    op.create_check_constraint(op.f('ck_app_user_app_user_contact_or_anon'), 'app_user', 'email IS NOT NULL OR phone IS NOT NULL OR anon_id IS NOT NULL', schema='app')
    op.create_check_constraint(op.f('ck_app_user_app_user_role_valid'), 'app_user', "role IN ('customer','staff','admin')", schema='app')
    op.drop_constraint(op.f('auth_session_token_hash_key'), 'auth_session', schema='app', type_='unique')
    op.create_unique_constraint(op.f('uq_auth_session_token_hash'), 'auth_session', ['token_hash'], schema='app')
    op.create_unique_constraint('uq_policy_block_ord', 'policy_block', ['document_id', 'ord'], schema='core')
    op.create_unique_constraint('uq_promotion_block_ord', 'promotion_block', ['promotion_id', 'ord'], schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_promotion_block_ord', 'promotion_block', schema='core', type_='unique')
    op.drop_constraint('uq_policy_block_ord', 'policy_block', schema='core', type_='unique')
    op.drop_constraint(op.f('uq_auth_session_token_hash'), 'auth_session', schema='app', type_='unique')
    op.create_unique_constraint(op.f('auth_session_token_hash_key'), 'auth_session', ['token_hash'], schema='app', postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('ck_app_user_app_user_role_valid'), 'app_user', schema='app', type_='check')
    op.drop_constraint(op.f('ck_app_user_app_user_contact_or_anon'), 'app_user', schema='app', type_='check')
    op.create_check_constraint(op.f('ck_app_user_role_valid'), 'app_user', "role = ANY (ARRAY['customer'::text, 'staff'::text, 'admin'::text])", schema='app')
    op.drop_constraint(op.f('uq_app_user_phone'), 'app_user', schema='app', type_='unique')
    op.create_index(op.f('uq_app_user_phone'), 'app_user', ['phone'], unique=True, schema='app', postgresql_where='(phone IS NOT NULL)')
    # ### end Alembic commands ###
