"""init core and app schema 48 tables

Revision ID: e1a3d9b2b327
Revises: 
Create Date: 2026-08-06 16:07:22.138540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1a3d9b2b327'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Extension: unaccent de tra dia danh khong dau, pg_trgm de khop mo ten
    # khach san (promotion_property_raw). Khong sinh tu model nen viet tay.
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenity',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=False),
    sa.Column('name_vi', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IS NULL OR category IN ('bathroom','tech','comfort','service','other')", name=op.f('ck_amenity_category_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_amenity'))
    )
    op.create_table('app_user',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('anon_id', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('locale', sa.Text(), server_default=sa.text("'vi'"), nullable=False),
    sa.Column('is_staff', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user')),
    sa.UniqueConstraint('anon_id', name=op.f('uq_app_user_anon_id')),
    sa.UniqueConstraint('email', name=op.f('uq_app_user_email'))
    )
    op.create_table('brand',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brand'))
    )
    op.create_table('destination',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=False),
    sa.Column('name_vi', sa.Text(), nullable=False),
    sa.Column('province', sa.Text(), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), server_default=sa.text("'Vietnam'"), nullable=False),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('has_content', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("region IS NULL OR region IN ('north','central','south')", name=op.f('ck_destination_region_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_destination'))
    )
    op.create_table('ingest_run',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('git_sha', sa.Text(), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('running','success','failed')", name=op.f('ck_ingest_run_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingest_run'))
    )
    op.create_table('media',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('alt', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IS NULL OR role IN ('hero','gallery','map','thumbnail')", name=op.f('ck_media_role_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media')),
    sa.UniqueConstraint('entity_type', 'entity_id', 'url', name='uq_media_entity_url')
    )
    op.create_index('ix_media_entity', 'media', ['entity_type', 'entity_id'], unique=False)
    op.create_table('data_quality_issue',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ingest_run_id', sa.BigInteger(), nullable=True),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('rule', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=True),
    sa.Column('entity_id', sa.Text(), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('json_path', sa.Text(), nullable=True),
    sa.Column('field', sa.Text(), nullable=True),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('error','warning','info')", name=op.f('ck_data_quality_issue_severity_valid')),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['ingest_run.id'], name=op.f('fk_data_quality_issue_ingest_run_id_ingest_run'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_quality_issue'))
    )
    op.create_index('ix_dqi_rule', 'data_quality_issue', ['rule'], unique=False)
    op.create_index('ix_dqi_run_severity', 'data_quality_issue', ['ingest_run_id', 'severity'], unique=False)
    op.create_table('destination_alias',
    sa.Column('destination_id', sa.Text(), nullable=False),
    sa.Column('alias_normalized', sa.Text(), nullable=False),
    sa.Column('alias', sa.Text(), nullable=False),
    sa.Column('origin', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("origin IS NULL OR origin IN ('crawl','manual')", name=op.f('ck_destination_alias_origin_valid')),
    sa.ForeignKeyConstraint(['destination_id'], ['destination.id'], name=op.f('fk_destination_alias_destination_id_destination'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('destination_id', 'alias_normalized', name=op.f('pk_destination_alias')),
    sa.UniqueConstraint('alias_normalized', name='uq_alias_normalized')
    )
    op.create_table('session',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('client_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("channel IS NULL OR channel IN ('web','api')", name=op.f('ck_session_channel_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_session_user_id_app_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session'))
    )
    op.create_table('source',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=True),
    sa.Column('domain', sa.Text(), nullable=True),
    sa.Column('brand_id', sa.Text(), nullable=True),
    sa.Column('source_language', sa.String(length=2), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('is_404', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('html_filename', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source_language IS NULL OR source_language IN ('vi','en')", name=op.f('ck_source_lang_valid')),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], name=op.f('fk_source_brand_id_brand')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source')),
    sa.UniqueConstraint('url', name=op.f('uq_source_url'))
    )
    op.create_table('complex',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('destination_id', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=True),
    sa.Column('ingest_run_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IS NULL OR kind IN ('united_center','park_complex','island')", name=op.f('ck_complex_kind_valid')),
    sa.ForeignKeyConstraint(['destination_id'], ['destination.id'], name=op.f('fk_complex_destination_id_destination')),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['ingest_run.id'], name=op.f('fk_complex_ingest_run_id_ingest_run'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('fk_complex_source_id_source'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_complex'))
    )
    op.create_table('entity_source',
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IS NULL OR role IN ('primary','secondary','detail')", name=op.f('ck_entity_source_role_valid')),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('fk_entity_source_source_id_source'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_type', 'entity_id', 'source_id', name=op.f('pk_entity_source'))
    )
    op.create_table('event_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.Text(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], name=op.f('fk_event_log_session_id_session'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_event_log_user_id_app_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_log'))
    )
    op.create_index('ix_event_log_ts', 'event_log', ['ts'], unique=False)
    op.create_table('faq',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('subcategory', sa.Text(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('destination_id', sa.Text(), nullable=True),
    sa.Column('content_language', sa.String(length=2), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=True),
    sa.Column('ingest_run_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destination.id'], name=op.f('fk_faq_destination_id_destination')),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['ingest_run.id'], name=op.f('fk_faq_ingest_run_id_ingest_run'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('fk_faq_source_id_source'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_faq'))
    )
    op.create_index('ix_faq_category', 'faq', ['category', 'subcategory'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('route', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('finish_reason', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user','assistant','system','tool')", name=op.f('ck_message_role_valid')),
    sa.CheckConstraint("route IS NULL OR route IN ('greeting','out_of_scope','rag')", name=op.f('ck_message_route_valid')),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], name=op.f('fk_message_session_id_session'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_message_user_id_app_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message')),
    sa.UniqueConstraint('session_id', 'seq', name='uq_message_session_seq')
    )
    op.create_index('ix_message_session_seq', 'message', ['session_id', 'seq'], unique=False)
    op.create_table('org_info',
    sa.Column('id', sa.SmallInteger(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('introduction', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('hotline', sa.Text(), nullable=True),
    sa.Column('account_holder', sa.Text(), nullable=True),
    sa.Column('bank_account', sa.Text(), nullable=True),
    sa.Column('bank', sa.Text(), nullable=True),
    sa.Column('business_registration', sa.Text(), nullable=True),
    sa.Column('issued_by', sa.Text(), nullable=True),
    sa.Column('mice_intro_title', sa.Text(), nullable=True),
    sa.Column('mice_intro_description', sa.Text(), nullable=True),
    sa.Column('mice_intro_cta', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=True),
    sa.Column('ingest_run_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name=op.f('ck_org_info_single_row')),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['ingest_run.id'], name=op.f('fk_org_info_ingest_run_id_ingest_run'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('fk_org_info_source_id_source'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_org_info'))
    )
    op.create_table('page_link',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('from_source_id', sa.Text(), nullable=False),
    sa.Column('to_url', sa.Text(), nullable=False),
    sa.Column('to_source_id', sa.Text(), nullable=True),
    sa.Column('anchor_text', sa.Text(), nullable=True),
    sa.Column('is_internal', sa.Boolean(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("context IS NULL OR context IN ('card','body','related','detail','option')", name=op.f('ck_page_link_context_valid')),
    sa.ForeignKeyConstraint(['from_source_id'], ['source.id'], name=op.f('fk_page_link_from_source_id_source'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_source_id'], ['source.id'], name=op.f('fk_page_link_to_source_id_source'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_page_link'))
    )
    op.create_index('ix_page_link_from', 'page_link', ['from_source_id'], unique=False)
    op.create_table('policy_document',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('h1', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('plain_text', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=True),
    sa.Column('ingest_run_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['ingest_run.id'], name=op.f('fk_policy_document_ingest_run_id_ingest_run'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('fk_policy_document_source_id_source'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_document'))
    )
    op.create_table('promotion',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('is_nationwide', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('booking_from', sa.Date(), nullable=True),
    sa.Column('booking_to', sa.Date(), nullable=True),
    sa.Column('booking_raw', sa.Text(), nullable=True),
    sa.Column('stay_from', sa.Date(), nullable=True),
    sa.Column('stay_to', sa.Date(), nullable=True),
    sa.Column('stay_raw', sa.Text(), nullable=True),
    sa.Column('validity_from', sa.Date(), nullable=True),
    sa.Column('validity_to', sa.Date(), nullable=True),
    sa.Column('validity_raw', sa.Text(), nullable=True),
    sa.Column('purchase_from', sa.Date(), nullable=True),
    sa.Column('purchase_to', sa.Date(), nullable=True),
    sa.Column('purchase_raw', sa.Text(), nullable=True),
    sa.Column('redemption_from', sa.Date(), nullable=True),
    sa.Column('redemption_to', sa.Date(), nullable=True),
    sa.Column('redemption_raw', sa.Text(), nullable=True),
    sa.Column('excluded_dates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recurring_schedule', sa.Text(), nullable=True),
    sa.Column('date_confidence', sa.Text(), nullable=True),
    sa.Column('status_at_crawl', sa.Text(), nullable=True),
    sa.Column('status_reason_raw', sa.Text(), nullable=True),
    sa.Column('status_calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=True),
    sa.Column('brand_id', sa.Text(), nullable=True),
    sa.Column('booking_url', sa.Text(), nullable=True),
    sa.Column('app_url', sa.Text(), nullable=True),
    sa.Column('terms_url', sa.Text(), nullable=True),
    sa.Column('content_language', sa.String(length=2), nullable=True),
    sa.Column('discount_text', sa.Text(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('crawl_method', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=True),
    sa.Column('ingest_run_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("date_confidence IS NULL OR date_confidence IN ('parsed','partial','unknown')", name=op.f('ck_promotion_date_confidence_valid')),
    sa.CheckConstraint("status_at_crawl IS NULL OR status_at_crawl IN ('active','upcoming','expired','unknown')", name=op.f('ck_promotion_status_at_crawl_valid')),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], name=op.f('fk_promotion_brand_id_brand')),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['ingest_run.id'], name=op.f('fk_promotion_ingest_run_id_ingest_run'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('fk_promotion_source_id_source'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promotion'))
    )
    op.create_index('ix_promotion_validity', 'promotion', ['validity_to'], unique=False, postgresql_where=sa.text('is_active'))
    op.create_table('attraction',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('destination_id', sa.Text(), nullable=False),
    sa.Column('complex_id', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Text(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('location_text', sa.Text(), nullable=True),
    sa.Column('section_title', sa.Text(), nullable=True),
    sa.Column('topic_group', sa.Text(), nullable=True),
    sa.Column('detail_url', sa.Text(), nullable=True),
    sa.Column('detail_status', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('content_language', sa.String(length=2), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('duration_nights', sa.Integer(), nullable=True),
    sa.Column('duration_label', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=True),
    sa.Column('ingest_run_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("detail_status IS NULL OR detail_status IN ('available','missing_url','not_found','not_provided')", name=op.f('ck_attraction_detail_status_valid')),
    sa.CheckConstraint("kind IN ('park','show','game','event','experience','journey','itinerary')", name=op.f('ck_attraction_kind_valid')),
    sa.ForeignKeyConstraint(['complex_id'], ['complex.id'], name=op.f('fk_attraction_complex_id_complex')),
    sa.ForeignKeyConstraint(['destination_id'], ['destination.id'], name=op.f('fk_attraction_destination_id_destination')),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['ingest_run.id'], name=op.f('fk_attraction_ingest_run_id_ingest_run'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['attraction.id'], name=op.f('fk_attraction_parent_id_attraction'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('fk_attraction_source_id_source'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attraction'))
    )
    op.create_index('ix_attraction_destination_kind', 'attraction', ['destination_id', 'kind'], unique=False)
    op.create_index('ix_attraction_parent', 'attraction', ['parent_id'], unique=False)
    op.create_table('destination_highlight',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('destination_id', sa.Text(), nullable=False),
    sa.Column('complex_id', sa.Text(), nullable=True),
    sa.Column('section_title', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=True),
    sa.Column('ingest_run_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['complex_id'], ['complex.id'], name=op.f('fk_destination_highlight_complex_id_complex')),
    sa.ForeignKeyConstraint(['destination_id'], ['destination.id'], name=op.f('fk_destination_highlight_destination_id_destination')),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['ingest_run.id'], name=op.f('fk_destination_highlight_ingest_run_id_ingest_run'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('fk_destination_highlight_source_id_source'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_destination_highlight'))
    )
    op.create_table('golf_course',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('destination_id', sa.Text(), nullable=False),
    sa.Column('complex_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('page_url', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('designer', sa.Text(), nullable=True),
    sa.Column('holes', sa.Integer(), nullable=True),
    sa.Column('par', sa.Integer(), nullable=True),
    sa.Column('course_length_raw', sa.Text(), nullable=True),
    sa.Column('total_area', sa.Text(), nullable=True),
    sa.Column('terrain', sa.Text(), nullable=True),
    sa.Column('full_address', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('district', sa.Text(), nullable=True),
    sa.Column('island', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=True),
    sa.Column('ingest_run_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['complex_id'], ['complex.id'], name=op.f('fk_golf_course_complex_id_complex')),
    sa.ForeignKeyConstraint(['destination_id'], ['destination.id'], name=op.f('fk_golf_course_destination_id_destination')),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['ingest_run.id'], name=op.f('fk_golf_course_ingest_run_id_ingest_run'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('fk_golf_course_source_id_source'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_golf_course'))
    )
    op.create_table('message_citation',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=True),
    sa.Column('entity_id', sa.Text(), nullable=True),
    sa.Column('chunk_id', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], name=op.f('fk_message_citation_message_id_message'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'rank', name=op.f('pk_message_citation'))
    )
    op.create_table('message_feedback',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating IN (-1, 1)', name=op.f('ck_message_feedback_rating_valid')),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], name=op.f('fk_message_feedback_message_id_message'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_message_feedback_user_id_app_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_feedback')),
    sa.UniqueConstraint('message_id', name=op.f('uq_message_feedback_message_id'))
    )
    op.create_table('policy_block',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('document_id', sa.Text(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.Text(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("block_type IN ('table','list')", name=op.f('ck_policy_block_block_type_valid')),
    sa.ForeignKeyConstraint(['document_id'], ['policy_document.id'], name=op.f('fk_policy_block_document_id_policy_document'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_block'))
    )
    op.create_table('policy_section',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('document_id', sa.Text(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('heading', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['policy_document.id'], name=op.f('fk_policy_section_document_id_policy_document'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_section')),
    sa.UniqueConstraint('document_id', 'ord', name='uq_policy_section_ord')
    )
    op.create_table('promotion_benefit',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('promotion_id', sa.Text(), nullable=False),
    sa.Column('benefit_type', sa.Text(), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('is_maximum', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("benefit_type IN ('percentage_discount','voucher','upgrade','hotel_credit','multiplier','fixed_amount_discount','gift','free_ticket')", name=op.f('ck_promotion_benefit_benefit_type_valid')),
    sa.CheckConstraint("unit IS NULL OR unit IN ('percent','VND','times')", name=op.f('ck_promotion_benefit_unit_valid')),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotion.id'], name=op.f('fk_promotion_benefit_promotion_id_promotion'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promotion_benefit'))
    )
    op.create_table('promotion_block',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('promotion_id', sa.Text(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.Text(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("block_type IN ('table','bullet_list','heading')", name=op.f('ck_promotion_block_block_type_valid')),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotion.id'], name=op.f('fk_promotion_block_promotion_id_promotion'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promotion_block'))
    )
    op.create_table('promotion_code',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('promotion_id', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('validity', sa.Text(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_suspect', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotion.id'], name=op.f('fk_promotion_code_promotion_id_promotion'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promotion_code'))
    )
    op.create_table('promotion_destination',
    sa.Column('promotion_id', sa.Text(), nullable=False),
    sa.Column('destination_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destination.id'], name=op.f('fk_promotion_destination_destination_id_destination'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotion.id'], name=op.f('fk_promotion_destination_promotion_id_promotion'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('promotion_id', 'destination_id', name=op.f('pk_promotion_destination'))
    )
    op.create_table('promotion_relation',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('promotion_id', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('target_url', sa.Text(), nullable=True),
    sa.Column('target_promotion_id', sa.Text(), nullable=True),
    sa.Column('target_brand_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('related_promotion','related_brand','related_article')", name=op.f('ck_promotion_relation_kind_valid')),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotion.id'], name=op.f('fk_promotion_relation_promotion_id_promotion'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_brand_id'], ['brand.id'], name=op.f('fk_promotion_relation_target_brand_id_brand')),
    sa.ForeignKeyConstraint(['target_promotion_id'], ['promotion.id'], name=op.f('fk_promotion_relation_target_promotion_id_promotion'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promotion_relation'))
    )
    op.create_table('promotion_section',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('promotion_id', sa.Text(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('heading', sa.Text(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotion.id'], name=op.f('fk_promotion_section_promotion_id_promotion'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promotion_section')),
    sa.UniqueConstraint('promotion_id', 'ord', name='uq_promotion_section_ord')
    )
    op.create_table('promotion_step',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('promotion_id', sa.Text(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotion.id'], name=op.f('fk_promotion_step_promotion_id_promotion'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promotion_step')),
    sa.UniqueConstraint('promotion_id', 'ord', name='uq_promotion_step_ord')
    )
    op.create_table('promotion_tag',
    sa.Column('promotion_id', sa.Text(), nullable=False),
    sa.Column('tag_type', sa.Text(), nullable=False),
    sa.Column('tag_value', sa.Text(), nullable=False),
    sa.CheckConstraint("tag_type IN ('promotion_type','service','channel','customer_group','member_tier')", name=op.f('ck_promotion_tag_tag_type_valid')),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotion.id'], name=op.f('fk_promotion_tag_promotion_id_promotion'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('promotion_id', 'tag_type', 'tag_value', name=op.f('pk_promotion_tag'))
    )
    op.create_index('ix_promotion_tag_type_value', 'promotion_tag', ['tag_type', 'tag_value'], unique=False)
    op.create_table('promotion_term',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('promotion_id', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('term','combination','contact')", name=op.f('ck_promotion_term_kind_valid')),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotion.id'], name=op.f('fk_promotion_term_promotion_id_promotion'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promotion_term'))
    )
    op.create_table('property',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=True),
    sa.Column('destination_id', sa.Text(), nullable=False),
    sa.Column('complex_id', sa.Text(), nullable=True),
    sa.Column('brand_id', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('room_page_url', sa.Text(), nullable=True),
    sa.Column('dining_page_url', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=True),
    sa.Column('ingest_run_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IS NULL OR kind IN ('hotel','resort')", name=op.f('ck_property_kind_valid')),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], name=op.f('fk_property_brand_id_brand')),
    sa.ForeignKeyConstraint(['complex_id'], ['complex.id'], name=op.f('fk_property_complex_id_complex')),
    sa.ForeignKeyConstraint(['destination_id'], ['destination.id'], name=op.f('fk_property_destination_id_destination')),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['ingest_run.id'], name=op.f('fk_property_ingest_run_id_ingest_run'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('fk_property_source_id_source'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property'))
    )
    op.create_index('ix_property_destination', 'property', ['destination_id'], unique=False)
    op.create_table('ticket',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.Text(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'open'"), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('priority', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('assignee', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("priority IS NULL OR priority IN ('low','normal','high')", name=op.f('ck_ticket_priority_valid')),
    sa.CheckConstraint("status IN ('open','in_progress','resolved','closed')", name=op.f('ck_ticket_status_valid')),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], name=op.f('fk_ticket_message_id_message'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], name=op.f('fk_ticket_session_id_session'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_ticket_user_id_app_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket'))
    )
    op.create_index('ix_ticket_status', 'ticket', ['status'], unique=False)
    op.create_table('attraction_itinerary_day',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('attraction_id', sa.Text(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('heading', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('activities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attraction_id'], ['attraction.id'], name=op.f('fk_attraction_itinerary_day_attraction_id_attraction'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attraction_itinerary_day')),
    sa.UniqueConstraint('attraction_id', 'day_number', name='uq_itinerary_day')
    )
    op.create_table('dining_service',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('property_id', sa.Text(), nullable=False),
    sa.Column('service_index', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('opens_at', sa.Time(), nullable=True),
    sa.Column('closes_at', sa.Time(), nullable=True),
    sa.Column('hours_raw', sa.Text(), nullable=True),
    sa.Column('hours_display', sa.Text(), nullable=True),
    sa.Column('contact_raw', sa.Text(), nullable=True),
    sa.Column('contact_display', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=True),
    sa.Column('ingest_run_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['ingest_run.id'], name=op.f('fk_dining_service_ingest_run_id_ingest_run'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], name=op.f('fk_dining_service_property_id_property'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('fk_dining_service_source_id_source'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dining_service'))
    )
    op.create_table('golf_course_map',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('course_id', sa.Text(), nullable=False),
    sa.Column('course_type', sa.Text(), nullable=True),
    sa.Column('map_name', sa.Text(), nullable=True),
    sa.Column('map_url', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=True),
    sa.Column('ingest_run_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['golf_course.id'], name=op.f('fk_golf_course_map_course_id_golf_course'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['ingest_run.id'], name=op.f('fk_golf_course_map_ingest_run_id_ingest_run'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('fk_golf_course_map_source_id_source'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_golf_course_map'))
    )
    op.create_table('golf_feature',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('course_id', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('detail_url', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=True),
    sa.Column('ingest_run_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('feature','award','amenity','experience')", name=op.f('ck_golf_feature_kind_valid')),
    sa.ForeignKeyConstraint(['course_id'], ['golf_course.id'], name=op.f('fk_golf_feature_course_id_golf_course'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['ingest_run.id'], name=op.f('fk_golf_feature_ingest_run_id_ingest_run'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('fk_golf_feature_source_id_source'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_golf_feature'))
    )
    op.create_table('mice_venue',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('destination_id', sa.Text(), nullable=False),
    sa.Column('complex_id', sa.Text(), nullable=True),
    sa.Column('property_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=True),
    sa.Column('ingest_run_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['complex_id'], ['complex.id'], name=op.f('fk_mice_venue_complex_id_complex')),
    sa.ForeignKeyConstraint(['destination_id'], ['destination.id'], name=op.f('fk_mice_venue_destination_id_destination')),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['ingest_run.id'], name=op.f('fk_mice_venue_ingest_run_id_ingest_run'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], name=op.f('fk_mice_venue_property_id_property')),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('fk_mice_venue_source_id_source'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mice_venue'))
    )
    op.create_table('org_highlight',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('destination_id', sa.Text(), nullable=True),
    sa.Column('property_id', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=True),
    sa.Column('ingest_run_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('hotel_resort','package','mice','meeting_event')", name=op.f('ck_org_highlight_kind_valid')),
    sa.ForeignKeyConstraint(['destination_id'], ['destination.id'], name=op.f('fk_org_highlight_destination_id_destination')),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['ingest_run.id'], name=op.f('fk_org_highlight_ingest_run_id_ingest_run'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], name=op.f('fk_org_highlight_property_id_property')),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('fk_org_highlight_source_id_source'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_org_highlight'))
    )
    op.create_table('promotion_property_raw',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('promotion_id', sa.Text(), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=False),
    sa.Column('matched_property_id', sa.Text(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['matched_property_id'], ['property.id'], name=op.f('fk_promotion_property_raw_matched_property_id_property'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotion.id'], name=op.f('fk_promotion_property_raw_promotion_id_promotion'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promotion_property_raw'))
    )
    op.create_table('room',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('property_id', sa.Text(), nullable=False),
    sa.Column('room_index', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('guest_count', sa.Integer(), nullable=True),
    sa.Column('area_sqm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('area_raw', sa.Text(), nullable=True),
    sa.Column('price_from_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_from_currency', sa.String(length=3), nullable=True),
    sa.Column('price_is_approximate', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('price_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rate_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rate_currency', sa.String(length=3), nullable=True),
    sa.Column('rate_raw', sa.Text(), nullable=True),
    sa.Column('is_rate_suspect', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('bed_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('has_wifi', sa.Boolean(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('page_url', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=True),
    sa.Column('ingest_run_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('guest_count IS NULL OR guest_count > 0', name=op.f('ck_room_guest_count_positive')),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['ingest_run.id'], name=op.f('fk_room_ingest_run_id_ingest_run'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], name=op.f('fk_room_property_id_property'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('fk_room_source_id_source'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room')),
    sa.UniqueConstraint('property_id', 'room_index', name='uq_room_property_index')
    )
    op.create_index('ix_room_price', 'room', ['price_from_amount'], unique=False, postgresql_where=sa.text('price_from_amount IS NOT NULL'))
    op.create_table('mice_room',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('venue_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('area_sqm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('area_raw', sa.Text(), nullable=True),
    sa.Column('length_m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('width_m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('ceiling_height_m', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('specifications_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=True),
    sa.Column('ingest_run_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['ingest_run.id'], name=op.f('fk_mice_room_ingest_run_id_ingest_run'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('fk_mice_room_source_id_source'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['venue_id'], ['mice_venue.id'], name=op.f('fk_mice_room_venue_id_mice_venue'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mice_room'))
    )
    op.create_table('room_amenity',
    sa.Column('room_id', sa.Text(), nullable=False),
    sa.Column('amenity_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenity.id'], name=op.f('fk_room_amenity_amenity_id_amenity'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name=op.f('fk_room_amenity_room_id_room'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id', 'amenity_id', name=op.f('pk_room_amenity'))
    )
    op.create_table('mice_room_capacity',
    sa.Column('room_id', sa.Text(), nullable=False),
    sa.Column('layout', sa.Text(), nullable=False),
    sa.Column('pax', sa.Integer(), nullable=False),
    sa.CheckConstraint("layout IN ('theater','classroom','u_shape','boardroom','banquet','cocktail')", name=op.f('ck_mice_room_capacity_layout_valid')),
    sa.CheckConstraint('pax > 0', name=op.f('ck_mice_room_capacity_pax_positive')),
    sa.ForeignKeyConstraint(['room_id'], ['mice_room.id'], name=op.f('fk_mice_room_capacity_room_id_mice_room'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id', 'layout', name=op.f('pk_mice_room_capacity'))
    )
    op.create_index('ix_mice_capacity_layout_pax', 'mice_room_capacity', ['layout', 'pax'], unique=False)
    # ### end Alembic commands ###

    # Index trigram cho khop mo ten khach san: promotion_property_raw chua 327
    # chuoi cut, phai khop bang do tuong tu chu khong bang dau bang.
    op.create_index(
        "ix_property_name_trgm",
        "property",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )

    # Trang thai uu dai tinh theo CURRENT_DATE, KHONG dung status_at_crawl
    # (tinh luc 2026-08-01 nen da cu ngay khi nap vao).
    op.execute(
        """
        CREATE VIEW promotion_active AS
        SELECT * FROM promotion
        WHERE is_active
          AND (booking_to  IS NULL OR booking_to  >= CURRENT_DATE)
          AND (validity_to IS NULL OR validity_to >= CURRENT_DATE)
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP VIEW IF EXISTS promotion_active")
    op.execute("DROP INDEX IF EXISTS ix_property_name_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mice_capacity_layout_pax', table_name='mice_room_capacity')
    op.drop_table('mice_room_capacity')
    op.drop_table('room_amenity')
    op.drop_table('mice_room')
    op.drop_index('ix_room_price', table_name='room', postgresql_where=sa.text('price_from_amount IS NOT NULL'))
    op.drop_table('room')
    op.drop_table('promotion_property_raw')
    op.drop_table('org_highlight')
    op.drop_table('mice_venue')
    op.drop_table('golf_feature')
    op.drop_table('golf_course_map')
    op.drop_table('dining_service')
    op.drop_table('attraction_itinerary_day')
    op.drop_index('ix_ticket_status', table_name='ticket')
    op.drop_table('ticket')
    op.drop_index('ix_property_destination', table_name='property')
    op.drop_table('property')
    op.drop_table('promotion_term')
    op.drop_index('ix_promotion_tag_type_value', table_name='promotion_tag')
    op.drop_table('promotion_tag')
    op.drop_table('promotion_step')
    op.drop_table('promotion_section')
    op.drop_table('promotion_relation')
    op.drop_table('promotion_destination')
    op.drop_table('promotion_code')
    op.drop_table('promotion_block')
    op.drop_table('promotion_benefit')
    op.drop_table('policy_section')
    op.drop_table('policy_block')
    op.drop_table('message_feedback')
    op.drop_table('message_citation')
    op.drop_table('golf_course')
    op.drop_table('destination_highlight')
    op.drop_index('ix_attraction_parent', table_name='attraction')
    op.drop_index('ix_attraction_destination_kind', table_name='attraction')
    op.drop_table('attraction')
    op.drop_index('ix_promotion_validity', table_name='promotion', postgresql_where=sa.text('is_active'))
    op.drop_table('promotion')
    op.drop_table('policy_document')
    op.drop_index('ix_page_link_from', table_name='page_link')
    op.drop_table('page_link')
    op.drop_table('org_info')
    op.drop_index('ix_message_session_seq', table_name='message')
    op.drop_table('message')
    op.drop_index('ix_faq_category', table_name='faq')
    op.drop_table('faq')
    op.drop_index('ix_event_log_ts', table_name='event_log')
    op.drop_table('event_log')
    op.drop_table('entity_source')
    op.drop_table('complex')
    op.drop_table('source')
    op.drop_table('session')
    op.drop_table('destination_alias')
    op.drop_index('ix_dqi_run_severity', table_name='data_quality_issue')
    op.drop_index('ix_dqi_rule', table_name='data_quality_issue')
    op.drop_table('data_quality_issue')
    op.drop_index('ix_media_entity', table_name='media')
    op.drop_table('media')
    op.drop_table('ingest_run')
    op.drop_table('destination')
    op.drop_table('brand')
    op.drop_table('app_user')
    op.drop_table('amenity')
    # ### end Alembic commands ###
