import { createContext, useContext, useState } from 'react'

const EN = {
  navHotels: 'Hotels & Resorts',
  navAbout: 'About Us',
  navExperiences: 'Experiences',
  navOffers: 'Offers & Combos',
  navNews: 'News',
  navMeetings: 'Meetings & Events',
  navRegulations: 'Policies',
  navSupport: 'Support',
  navAiChat: 'AI Concierge',
  signIn: 'Sign In',
  navRegister: 'Register',
  signOut: 'Sign Out',
  welcomeGuest: 'Welcome',
  heroTitle: 'Experience Unmatched Luxury & Serenity',
  heroSubtitle:
    'Discover world-class Vietnamese luxury destinations with VinTravel AI Personal Concierge.',
  searchDest: 'Destination',
  searchCheckIn: 'Check-in Date',
  searchCheckOut: 'Check-out Date',
  searchGuests: 'Guests',
  searchBudget: 'Max Budget / Night',
  btnSearch: 'Search Stays',
  btnAskAi: 'Ask AI Concierge',
  destTitle: 'Featured Destinations',
  destSubtitle: 'Handpicked paradises tailored for unforgettable moments',
  featuredHotels: 'Signature Resorts & Villas',
  offersTitle: 'Exclusive Combos & Special Packages',
  aiBannerTitle: 'Meet Your Personal Luxury AI Travel Companion',
  aiBannerDesc:
    'Get instantly personalized itineraries, budget allocation, child policies, and bespoke dining reservations in seconds.',
  startAiChat: 'Start Live AI Chat',
  filterTitle: 'Filter Stays',
  priceRange: 'Price Range / Night',
  accType: 'Property Type',
  amenities: 'Amenities',
  viewDetails: 'View Details',
  askAiAboutThis: 'Ask AI About This Place',
  planItinerary: 'Ask AI to Plan Itinerary',
  bookNow: 'Book Suite Now',
  policies: 'Resort Policies & Rules',
  createTicket: 'Escalate to Support Ticket',
  supportTitle: 'Customer Care & Escalation Center',
  submitTicket: 'Submit Support Ticket',
  ticketHistory: 'Your Submitted Tickets',
  statusPending: 'Pending Review',
  statusProcessing: 'In Progress',
  statusResolved: 'Resolved',
  allDestinations: 'All Destinations',
  allTypes: 'All Property Types',
  startingFrom: 'Starting from',
  perNight: 'VND / night',
  selectRoom: 'Select Suite',
  reservedSuccess: 'Suite reserved! Proceeding to instant confirmation.',
  overview: 'Overview & Features',
  availableSuites: 'Available Suites & Villas',
  checkInCheckOut: 'Check-in / Check-out',
  childrenPolicy: 'Children & Extra Bed Policy',
  cancellationPolicy: 'Cancellation Policy',
  paymentMethods: 'Accepted Payment Methods',
  portfolioEyebrow: 'Vinpearl Inspired Portfolio',
  portfoliosEyebrow: 'Vinpearl Inspired Portfolios',
  aiConciergeBadge: 'Multilingual AI Concierge',
  luxuryHospitality: 'Luxury Hospitality',
  viewAllResorts: 'View All Resorts',
  travelPackagesEyebrow: 'All-Inclusive Travel Packages',
  bookWithAi: 'Book with AI',
  exploreRetreats: 'Explore Retreats',
  priceUnitNight: 'VND / night',
  reviews: 'reviews',
  backToResorts: 'Back to Resorts',
  aboutPrefix: 'About',
  resortAmenitiesTitle: 'Resort Amenities & Features',
  checkInLabel: 'Check-in',
  checkOutLabel: 'Check-out',
  foundPrefix: 'Found',
  searchHeadingSuffix: 'Retreats & Villas',
  searchFoundText: 'luxury sanctuary properties matching your filter criteria',
  noMatchesTitle: 'No Exact Matches Found',
  noMatchesDesc:
    'Try adjusting your budget slider or destination filter. Alternatively, request our AI Concierge to curate custom options.',
  askAiCustomRecommendation: 'Ask AI Concierge for Custom Recommendation',
  chatWidgetTitle: 'VinTravel AI Concierge',
  chatWidgetOnline: 'Online - Multilingual Assistant',
  chatWidgetWelcome:
    'Welcome to VinTravel AI! How can I assist your luxury stay today?',
  chatWidgetTopics:
    '3D2N Itineraries - Child Policies - Villa Pricing - Special Offers',
  chatWidgetChipPhuQuoc: 'Phu Quoc 3D2N Luxury Villa Itinerary',
  chatWidgetChipFamily: 'Children & Family Policies',
  chatWidgetPlaceholder: 'Ask AI anything about your stay...',
  chatWidgetOpenFull: 'Open Full Chatbot Workspace',
  heroBadge: 'Multilingual AI Concierge Standard',
  heroTitleBefore: 'Pristine',
  heroTitleAccent: 'luxury',
  heroTitleAfter: 'Retreats',
  heroSubtitleCustom:
    'Experience the pinnacle of tropical sanctuary where azure waters meet white sand resorts.',
  heroAiHelp:
    'Need custom 3D2N itineraries or child policy details? Ask our AI Concierge.',
  resortsVillas: 'Resorts & Villas',
  luxuryRating: 'Luxury Rating',
  aiSupport: 'AI Support',
  adults2: '2 Adults',
  adults2Child1: '2 Adults + 1 Child',
  adults2Children2: '2 Adults + 2 Children',
  adults4Villa: '4 Adults (Ocean Villa)',
  adults6Estate: '6 Adults (3-Bedroom Estate)',
  footerDescription:
    'Vietnam premier luxury resort portfolio powered by advanced AI travel consultation. Tailored 3D2N itineraries, instant booking, and 24/7 personal concierge.',
  bestRateGuarantee: 'Best Rate Guarantee',
  fiveStarHospitality: '5-Star Hospitality',
  topDestinations: 'Top Destinations',
  aiConciergeServices: 'AI Concierge Services',
  realtimeConsultation: 'Real-time Travel Consultation',
  familyPlanner: 'Bespoke Family Itinerary Planner',
  policiesGuide: 'Resort Policies & Cancellation Guide',
  ticketCenter: 'Ticket Center',
  contactHotline: 'Contact & Hotline',
  footerAddress: 'VinTravel Tower, Landmark District, Ho Chi Minh City, Vietnam',
  footerCopyright: 'VinTravel Luxury Portfolio © 2026',
  privacy: 'Privacy',
  terms: 'Terms',
  backToHome: 'Back to Home',
  loginTitle: 'Welcome Back',
  loginSubtitle: 'Access your VinTravel AI luxury booking portal',
  emailAddress: 'Email Address',
  password: 'Password',
  noAccount: "Don't have an account?",
  registerHere: 'Register Here',
  registerTitle: 'Create Guest Account',
  registerSubtitle:
    'Join VinTravel AI for exclusive VIP perks and AI itineraries',
  fullName: 'Full Name',
  createAccount: 'Create Account',
  alreadyHaveAccount: 'Already have an account?',
  ticketBadge: '24/7 Human Concierge Escalation',
  ticketSubtitle:
    'When our AI Concierge requires custom human review for complex events, group bookings, or special dietary requirements.',
  ticketSuccessTitle: 'Support Ticket Submitted Successfully!',
  ticketSuccessDesc:
    'Our human concierge specialist will contact you via email/phone within 2 hours.',
  phoneZalo: 'Phone / Zalo',
  preferredLanguage: 'Preferred Language',
  subject: 'Subject',
  inquiryDetails: 'Inquiry Details',
  submittingTicket: 'Submitting Ticket...',
  submittedBy: 'Submitted by',
  dateLabel: 'Date',
  generalInquiry: 'General Resort Inquiry',
  loadingResortDetails: 'Loading VinTravel resort details...',
  clearChat: 'Clear Chat',
  resetConversation: 'Reset Conversation',
  liveAiBadge: 'Live Gemini AI',
  chatbotSubtitle: 'Multilingual Luxury Travel Specialist - EN - VI - KO - ZH',
  chatbotThinking: 'VinTravel AI Concierge is thinking and crafting itinerary...',
  chatbotEscalation: 'Need human concierge assistance for special group bookings?',
  chatbotSubmitTicket: 'Submit a Support Ticket',
  chatbotWelcome:
    'Welcome! I am your VinTravel AI Personal Concierge. I can assist with resort recommendations, custom 3D2N itineraries, budget breakdowns, and resort policy inquiries.',
  chatbotReset: 'Session restarted. How may I assist you now?',
  chatbotPlaceholder:
    'Ask about resorts, room prices, 3D2N itineraries, child policies...',
  reset: 'Reset',
  english: 'English',
  vietnamese: 'Vietnamese',
  korean: 'Korean',
  chinese: 'Chinese',
  footerPhuQuoc: 'Phu Quoc Island Resort & Golf',
  footerNhaTrang: 'Nha Trang Bay Cliffside Villas',
  footerHoiAn: 'Hoi An Heritage & Wellness Retreat',
  footerHaLong: 'Ha Long Bay Island Sanctuary',
  chatSuggestPhuQuoc: 'Phu Quoc 3D2N Villa',
  chatSuggestNhaTrang: 'Nha Trang + VinWonders',
  chatSuggestFamily: 'Family Child Policies',
  chatSuggestHoiAn: 'Hoi An Golf Retreat',
  vpAboutVinpearl: 'About Vinpearl',
  vpAboutUs: 'About us',
  vpContact: 'Contact',
  vpCareers: 'Careers',
  vpFAQ: 'FAQs',
  vpSitemap: 'Sitemap',
  vpTermsAndConditions: 'Terms & Policies',
  vpTermsGeneral: 'General Terms',
  vpTermsRegulations: 'General Regulations',
  vpTermsPayment: 'Payment Policy',
  vpTermsBooking: 'Booking Confirmation Policy',
  vpTermsDispute: 'Dispute Resolution Policy',
  vpTermsPrivacy: 'Privacy Policy',
  vpTermsTransparency: 'Transparency Policy',
  regulationsHome: 'Home',
  regulationsEyebrow: 'Vinpearl policy',
  regulationsDocumentInfo: 'Document information',
  regulationsDocumentCount: 'documents',
  regulationsSectionCount: 'content sections',
  regulationsSource: 'Source: Vinpearl',
  regulationsCategoryLabel: 'Categories',
  regulationsDocumentLabel: 'Document',
  regulationsFallbackDescription:
    'A collection of policies and regulations applied during booking, check-in, and service usage at Vinpearl.',
  regulationsBookingAppendix: 'Appendix 01: Booking contact list',
  regulationsAccountAppendix: 'Appendix 02: Account list',
  vpTermsInvestors: 'Investor Relations',
  vpTermsSustainability: 'Sustainability',
  vpNewsAndEvents: 'News & Events',
  vpNewsCompany: 'Company News',
  vpNewsGuide: 'Travel Guide',
  vpNewsAchievements: 'Achievements',
  vpNewsLegal: 'Legal Announcements',
  vpTagPhuQuoc: 'Phu Quoc Travel',
  vpTagNhaTrang: 'Nha Trang Travel',
  vpTagHoiAn: 'Hoi An Travel',
  vpTagHaLong: 'Ha Long Travel',
  vpTagVietnam: 'Vietnam Travel',
  vpScanQR: 'Scan QR to download app',
}

const VI = {
  navHotels: 'Khách sạn',
  navAbout: 'Giới thiệu',
  navExperiences: 'Trải nghiệm',
  navOffers: 'Ưu đãi & Combo',
  navNews: 'Tin tức',
  navMeetings: 'Hội họp & Sự kiện',
  navRegulations: 'Chính sách',
  navSupport: 'Hỗ trợ',
  navAiChat: 'Trợ lý AI',
  signIn: 'Đăng nhập',
  navRegister: 'Đăng ký',
  signOut: 'Đăng xuất',
  welcomeGuest: 'Xin chào',
  heroTitle: 'Trải nghiệm nghỉ dưỡng sang trọng và yên bình',
  heroSubtitle:
    'Khám phá các điểm đến nghỉ dưỡng Việt Nam đẳng cấp cùng trợ lý cá nhân VinTravel AI.',
  searchDest: 'Điểm đến',
  searchCheckIn: 'Ngày nhận phòng',
  searchCheckOut: 'Ngày trả phòng',
  searchGuests: 'Số khách',
  searchBudget: 'Ngân sách tối đa / đêm',
  btnSearch: 'Tìm nơi nghỉ',
  btnAskAi: 'Hỏi trợ lý AI',
  destTitle: 'Điểm đến nổi bật',
  destSubtitle: 'Những thiên đường nghỉ dưỡng được chọn lọc cho kỳ nghỉ đáng nhớ',
  featuredHotels: 'Khu nghỉ dưỡng & biệt thự nổi bật',
  offersTitle: 'Combo và gói ưu đãi độc quyền',
  aiBannerTitle: 'Gặp gỡ trợ lý du lịch AI cá nhân của bạn',
  aiBannerDesc:
    'Nhận lịch trình cá nhân hóa, phân bổ ngân sách, chính sách trẻ em và gợi ý đặt bàn riêng chỉ trong vài giây.',
  startAiChat: 'Bắt đầu trò chuyện với AI',
  filterTitle: 'Bộ lọc nơi nghỉ',
  priceRange: 'Khoảng giá / đêm',
  accType: 'Loại hình lưu trú',
  amenities: 'Tiện ích',
  viewDetails: 'Xem chi tiết',
  askAiAboutThis: 'Hỏi AI về nơi này',
  planItinerary: 'Nhờ AI lập lịch trình',
  bookNow: 'Đặt phòng ngay',
  policies: 'Chính sách & quy định',
  createTicket: 'Chuyển sang phiếu hỗ trợ',
  supportTitle: 'Trung tâm chăm sóc khách hàng',
  submitTicket: 'Gửi phiếu hỗ trợ',
  ticketHistory: 'Phiếu hỗ trợ đã gửi',
  statusPending: 'Đang chờ xử lý',
  statusProcessing: 'Đang xử lý',
  statusResolved: 'Đã giải quyết',
  allDestinations: 'Tất cả điểm đến',
  allTypes: 'Tất cả loại hình',
  startingFrom: 'Giá từ',
  perNight: 'VND / đêm',
  selectRoom: 'Chọn hạng phòng',
  reservedSuccess: 'Đã chọn phòng thành công! Đang chuyển sang xác nhận.',
  overview: 'Tổng quan & tiện ích',
  availableSuites: 'Hạng phòng & biệt thự còn trống',
  checkInCheckOut: 'Nhận / trả phòng',
  childrenPolicy: 'Chính sách trẻ em & giường phụ',
  cancellationPolicy: 'Chính sách hủy phòng',
  paymentMethods: 'Phương thức thanh toán',
  portfolioEyebrow: 'Bộ sưu tập lấy cảm hứng từ Vinpearl',
  portfoliosEyebrow: 'Bộ sưu tập lấy cảm hứng từ Vinpearl',
  aiConciergeBadge: 'Trợ lý AI đa ngôn ngữ',
  luxuryHospitality: 'Dịch vụ nghỉ dưỡng cao cấp',
  viewAllResorts: 'Xem tất cả resort',
  travelPackagesEyebrow: 'Gói du lịch trọn gói',
  bookWithAi: 'Đặt với AI',
  exploreRetreats: 'Khám phá nơi nghỉ',
  priceUnitNight: 'VND / đêm',
  reviews: 'đánh giá',
  backToResorts: 'Quay lại danh sách resort',
  aboutPrefix: 'Giới thiệu',
  resortAmenitiesTitle: 'Tiện ích & điểm nổi bật của resort',
  checkInLabel: 'Nhận phòng',
  checkOutLabel: 'Trả phòng',
  foundPrefix: 'Tìm thấy',
  searchHeadingSuffix: 'Resort & biệt thự',
  searchFoundText: 'nơi nghỉ cao cấp phù hợp với bộ lọc của bạn',
  noMatchesTitle: 'Không tìm thấy kết quả phù hợp',
  noMatchesDesc:
    'Hãy thử điều chỉnh ngân sách hoặc điểm đến. Bạn cũng có thể nhờ trợ lý AI gợi ý lựa chọn riêng.',
  askAiCustomRecommendation: 'Nhờ trợ lý AI gợi ý riêng',
  chatWidgetTitle: 'Trợ lý VinTravel AI',
  chatWidgetOnline: 'Đang trực tuyến - Hỗ trợ đa ngôn ngữ',
  chatWidgetWelcome:
    'Chào mừng đến với VinTravel AI! Tôi có thể hỗ trợ kỳ nghỉ của bạn như thế nào?',
  chatWidgetTopics:
    'Lịch trình 3N2Đ - Chính sách trẻ em - Giá biệt thự - Ưu đãi đặc biệt',
  chatWidgetChipPhuQuoc: 'Lịch trình biệt thự cao cấp Phú Quốc 3N2Đ',
  chatWidgetChipFamily: 'Chính sách trẻ em & gia đình',
  chatWidgetPlaceholder: 'Hỏi AI bất kỳ điều gì về kỳ nghỉ của bạn...',
  chatWidgetOpenFull: 'Mở trang chatbot đầy đủ',
  heroBadge: 'Tiêu chuẩn trợ lý AI đa ngôn ngữ',
  heroTitleBefore: 'Những kỳ nghỉ',
  heroTitleAccent: 'sang trọng',
  heroTitleAfter: 'giữa thiên nhiên',
  heroSubtitleCustom:
    'Trải nghiệm không gian nghỉ dưỡng nhiệt đới nơi làn nước xanh gặp bãi cát trắng.',
  heroAiHelp:
    'Cần lịch trình 3N2Đ hoặc thông tin chính sách trẻ em? Hãy hỏi trợ lý AI.',
  resortsVillas: 'Resort & biệt thự',
  luxuryRating: 'Chuẩn nghỉ dưỡng',
  aiSupport: 'Hỗ trợ AI',
  adults2: '2 người lớn',
  adults2Child1: '2 người lớn + 1 trẻ em',
  adults2Children2: '2 người lớn + 2 trẻ em',
  adults4Villa: '4 người lớn (biệt thự biển)',
  adults6Estate: '6 người lớn (villa 3 phòng ngủ)',
  footerDescription:
    'Bộ sưu tập resort cao cấp tại Việt Nam với tư vấn du lịch AI, lịch trình 3N2Đ cá nhân hóa, đặt phòng nhanh và concierge cá nhân 24/7.',
  bestRateGuarantee: 'Cam kết giá tốt',
  fiveStarHospitality: 'Dịch vụ 5 sao',
  topDestinations: 'Điểm đến hàng đầu',
  aiConciergeServices: 'Dịch vụ trợ lý AI',
  realtimeConsultation: 'Tư vấn du lịch thời gian thực',
  familyPlanner: 'Lập lịch trình gia đình riêng',
  policiesGuide: 'Hướng dẫn chính sách & hủy phòng',
  ticketCenter: 'Trung tâm phiếu hỗ trợ',
  contactHotline: 'Liên hệ & hotline',
  footerAddress: 'Tòa nhà VinTravel, Quận Landmark, Thành phố Hồ Chí Minh, Việt Nam',
  footerCopyright: 'VinTravel Luxury Portfolio © 2026',
  privacy: 'Quyền riêng tư',
  terms: 'Điều khoản',
  backToHome: 'Quay lại trang chủ',
  loginTitle: 'Chào mừng trở lại',
  loginSubtitle: 'Truy cập cổng đặt phòng cao cấp VinTravel AI',
  emailAddress: 'Địa chỉ email',
  password: 'Mật khẩu',
  noAccount: 'Chưa có tài khoản?',
  registerHere: 'Đăng ký tại đây',
  registerTitle: 'Tạo tài khoản khách',
  registerSubtitle:
    'Tham gia VinTravel AI để nhận đặc quyền VIP và lịch trình AI riêng',
  fullName: 'Họ và tên',
  createAccount: 'Tạo tài khoản',
  alreadyHaveAccount: 'Đã có tài khoản?',
  ticketBadge: 'Chuyển hỗ trợ concierge 24/7',
  ticketSubtitle:
    'Dành cho yêu cầu cần nhân viên xem xét như sự kiện phức tạp, đặt đoàn hoặc nhu cầu ăn uống đặc biệt.',
  ticketSuccessTitle: 'Gửi phiếu hỗ trợ thành công!',
  ticketSuccessDesc:
    'Chuyên viên concierge sẽ liên hệ với bạn qua email/điện thoại trong vòng 2 giờ.',
  phoneZalo: 'Điện thoại / Zalo',
  preferredLanguage: 'Ngôn ngữ ưu tiên',
  subject: 'Chủ đề',
  inquiryDetails: 'Nội dung yêu cầu',
  submittingTicket: 'Đang gửi phiếu...',
  submittedBy: 'Người gửi',
  dateLabel: 'Ngày',
  generalInquiry: 'Yêu cầu tư vấn resort',
  loadingResortDetails: 'Đang tải chi tiết resort VinTravel...',
  clearChat: 'Xóa trò chuyện',
  resetConversation: 'Làm mới cuộc trò chuyện',
  liveAiBadge: 'Gemini AI trực tuyến',
  chatbotSubtitle: 'Chuyên viên du lịch cao cấp đa ngôn ngữ - EN - VI - KO - ZH',
  chatbotThinking: 'VinTravel AI đang suy nghĩ và xây dựng lịch trình...',
  chatbotEscalation: 'Cần concierge hỗ trợ đặt đoàn hoặc yêu cầu đặc biệt?',
  chatbotSubmitTicket: 'Gửi phiếu hỗ trợ',
  chatbotWelcome:
    'Xin chào quý khách! Tôi là VinTravel AI Concierge. Tôi có thể tư vấn resort, lịch trình 3 ngày 2 đêm, ngân sách và chính sách trẻ em.',
  chatbotReset: 'Cuộc trò chuyện đã được làm mới. Tôi có thể hỗ trợ gì cho bạn?',
  chatbotPlaceholder:
    'Nhập câu hỏi về resort, giá phòng, lịch trình 3N2Đ, chính sách trẻ em...',
  reset: 'Đặt lại',
  english: 'Tiếng Anh',
  vietnamese: 'Tiếng Việt',
  korean: 'Tiếng Hàn',
  chinese: 'Tiếng Trung',
  footerPhuQuoc: 'Resort & sân golf đảo Phú Quốc',
  footerNhaTrang: 'Biệt thự vịnh Nha Trang',
  footerHoiAn: 'Nghỉ dưỡng di sản & wellness Hội An',
  footerHaLong: 'Nghỉ dưỡng đảo vịnh Hạ Long',
  chatSuggestPhuQuoc: 'Villa Phú Quốc 3N2Đ',
  chatSuggestNhaTrang: 'Nha Trang + VinWonders',
  chatSuggestFamily: 'Chính sách trẻ em',
  chatSuggestHoiAn: 'Kỳ nghỉ golf Hội An',
  vpAboutVinpearl: 'Về Vinpearl',
  vpAboutUs: 'Giới thiệu về chúng tôi',
  vpContact: 'Liên hệ',
  vpCareers: 'Tuyển dụng',
  vpFAQ: 'Câu hỏi thường gặp',
  vpSitemap: 'Bản đồ trang',
  vpTermsAndConditions: 'Điều khoản & Quy định',
  vpTermsGeneral: 'Điều khoản chung',
  vpTermsRegulations: 'Quy định chung',
  vpTermsPayment: 'Quy định về thanh toán',
  vpTermsBooking: 'Quy định về xác nhận thông tin đặt phòng',
  vpTermsDispute: 'Chính sách giải quyết tranh chấp',
  vpTermsPrivacy: 'Chính sách Bảo vệ Dữ liệu cá nhân',
  vpTermsTransparency: 'Quy chế đảm bảo sự minh bạch',
  regulationsHome: 'Trang chủ',
  regulationsEyebrow: 'Chính sách Vinpearl',
  regulationsDocumentInfo: 'Thông tin tài liệu',
  regulationsDocumentCount: 'tài liệu',
  regulationsSectionCount: 'mục nội dung',
  regulationsSource: 'Nguồn: Vinpearl',
  regulationsCategoryLabel: 'Danh mục',
  regulationsDocumentLabel: 'Tài liệu',
  regulationsFallbackDescription:
    'Tổng hợp các chính sách và quy định áp dụng trong quá trình đặt, nhận phòng và sử dụng dịch vụ tại Vinpearl.',
  regulationsBookingAppendix: 'Phụ lục 01: Danh sách liên hệ đặt phòng',
  regulationsAccountAppendix: 'Phụ lục 02: Danh sách tài khoản',
  vpTermsInvestors: 'Quan hệ Cổ đông',
  vpTermsSustainability: 'Phát triển Bền vững',
  vpNewsAndEvents: 'Tin tức & Sự kiện',
  vpNewsCompany: 'Tin công ty',
  vpNewsGuide: 'Cẩm nang du lịch',
  vpNewsAchievements: 'Thành tựu',
  vpNewsLegal: 'Công bố pháp lý',
  vpTagPhuQuoc: 'Du lịch Phú Quốc',
  vpTagNhaTrang: 'Du lịch Nha Trang',
  vpTagHoiAn: 'Du lịch Hội An',
  vpTagHaLong: 'Du lịch Hạ Long',
  vpTagVietnam: 'Du lịch Việt Nam',
  vpScanQR: 'Quét QR để tải ứng dụng',
}

export const TRANSLATIONS = {
  EN,
  VI,
  KO: EN,
  ZH: EN,
}

const LanguageContext = createContext(undefined)

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('EN')
  const t = TRANSLATIONS[language] || TRANSLATIONS.EN

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
